import 'dotenv/config';
import mongoose from 'mongoose';
import { Category, Product } from '../models/index.js';

// Local images available in frontend/public/images/
// Product images map: use real category images as fallbacks
const IMG = {
  nida1:      '/images/p-jet-black-nida.jpg',
  nida2:      '/images/p-emerald-nida.jpg',
  nidaCat:    '/images/cat-nida-abaya.jpg',
  dubai1:     '/images/p-gold-dubai.jpg',
  dubai2:     '/images/p-maroon-kaftan.jpg',
  dubaiCat:   '/images/cat-dubai-kaftan-style.jpg',
  embCat:     '/images/cat-embroidered-abaya.jpg',
  casualCat:  '/images/cat-casual-daily-wear.jpg',
  partyCat:   '/images/cat-party-wear-abaya.jpg',
  kidsCat:    '/images/cat-kids-abaya.jpg',
};

const categoriesData = [
  {
    name: 'Nida Abaya',
    slug: 'nida-abaya',
    description: 'Classic and modern abayas crafted from premium Korean and Dubai Nida fabric.',
    image: IMG.nidaCat,
    displayOrder: 1,
    isActive: true,
    seo: {
      metaTitle: 'Nida Abaya Collection | Hayyatic',
      metaDesc: 'Shop premium Korean Nida abayas in timeless designs.',
      keywords: ['nida abaya', 'korean nida', 'black abaya'],
    },
  },
  {
    name: 'Dubai / Kaftan Style',
    slug: 'dubai-kaftan-style',
    description: 'Flowing Dubai style kaftans and batwing silhouettes for an effortless luxurious look.',
    image: IMG.dubaiCat,
    displayOrder: 2,
    isActive: true,
    seo: {
      metaTitle: 'Dubai & Kaftan Style Abayas | Hayyatic',
      metaDesc: 'Explore luxurious Dubai style and Kaftan abayas with elegant drape.',
      keywords: ['dubai kaftan', 'butterfly abaya', 'kaftan abaya'],
    },
  },
  {
    name: 'Embroidered Abaya',
    slug: 'embroidered-abaya',
    description: 'Intricately embroidered abayas featuring handwork, resham thread, and pearl details.',
    image: IMG.embCat,
    displayOrder: 3,
    isActive: true,
    seo: {
      metaTitle: 'Embroidered Abaya Collection | Hayyatic',
      metaDesc: 'Detailed embroidery work on premium fabrics for sophisticated modesty.',
      keywords: ['embroidered abaya', 'handwork abaya', 'designer abaya'],
    },
  },
  {
    name: 'Casual / Daily Wear',
    slug: 'casual-daily-wear',
    description: 'Comfortable, breathable everyday abayas for work, college, and daily errands.',
    image: IMG.casualCat,
    displayOrder: 4,
    isActive: true,
    seo: {
      metaTitle: 'Casual & Daily Wear Abayas | Hayyatic',
      metaDesc: 'Durable and breathable everyday modest fashion.',
      keywords: ['casual abaya', 'daily wear abaya', 'cotton linen abaya'],
    },
  },
  {
    name: 'Party Wear Abaya',
    slug: 'party-wear-abaya',
    description: 'Statement occasion wear abayas with velvet, sequins, and metallic embellishments.',
    image: IMG.partyCat,
    displayOrder: 5,
    isActive: true,
    seo: {
      metaTitle: 'Luxury Party Wear Abayas | Hayyatic',
      metaDesc: 'Glamorous abayas crafted for weddings, eid, and special occasions.',
      keywords: ['party wear abaya', 'velvet abaya', 'luxury abaya'],
    },
  },
  {
    name: 'Kids Abaya',
    slug: 'kids-abaya',
    description: 'Charming and comfortable modest wear designed specifically for young girls.',
    image: IMG.kidsCat,
    displayOrder: 6,
    isActive: true,
    seo: {
      metaTitle: 'Kids Abaya Collection | Hayyatic',
      metaDesc: 'Adorable and lightweight abayas for girls.',
      keywords: ['kids abaya', 'girls abaya', 'madrassa abaya'],
    },
  },
];

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) {
      throw new Error('MONGO_URI is not defined in environment variables.');
    }

    console.log('Connecting to MongoDB Atlas...');
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB Atlas successfully.');

    // Wipe ONLY Category and Product collections
    console.log('Wiping existing Category and Product collections...');
    await Category.deleteMany({});
    await Product.deleteMany({});
    console.log('Collections wiped.');

    // Insert Categories
    console.log('Inserting categories...');
    const createdCategories = await Category.insertMany(categoriesData);
    console.log(`${createdCategories.length} categories inserted successfully.`);

    // Map categories by slug for easy referencing
    const catMap = {};
    createdCategories.forEach((cat) => {
      catMap[cat.slug] = cat._id;
    });

    // Define 18 Products (3 per category)
    const productsData = [
      // 1. Nida Abaya (3 items)
      {
        name: 'Jet Black Nida Abaya with Kaaf Sleeves',
        slug: 'jet-black-nida-abaya-kaaf-sleeves',
        description: 'An elegant jet black abaya crafted from ultra-soft Korean Nida fabric featuring tailored Kaaf cuffs.',
        shortDescription: 'Jet black Korean Nida abaya with structured Kaaf sleeves.',
        category: catMap['nida-abaya'],
        price: 5500,
        salePrice: 4999,
        sku: 'HYT-NID-001',
        stock: 20,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Black'],
        fabric: 'Premium Korean Nida',
        careInstructions: 'Dry clean or gentle hand wash in cold water.',
        images: [
          { url: IMG.nida1, alt: 'Jet Black Nida Abaya Front View', order: 0 },
          { url: IMG.nidaCat, alt: 'Jet Black Nida Abaya Detail View', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['nida', 'black', 'kaaf sleeves', 'bestseller'],
        ratingAvg: 4.9,
        ratingCount: 15,
        soldCount: 42,
      },
      {
        name: 'Emerald Green Front-Open Nida Abaya',
        slug: 'emerald-green-front-open-nida-abaya',
        description: 'Vibrant emerald green front-open style abaya with press-stud closures and matching Sheila included.',
        shortDescription: 'Front-open emerald green Korean Nida coat style abaya.',
        category: catMap['nida-abaya'],
        price: 6200,
        salePrice: 5499,
        sku: 'HYT-NID-002',
        stock: 3,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Emerald Green'],
        fabric: 'Korean Nida',
        careInstructions: 'Hand wash cold, line dry in shade.',
        images: [
          { url: IMG.nida2, alt: 'Emerald Green Nida Abaya Front View', order: 0 },
          { url: IMG.nidaCat, alt: 'Emerald Green Nida Abaya Side View', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['emerald green', 'front open', 'nida'],
        ratingAvg: 4.7,
        ratingCount: 8,
        soldCount: 19,
      },
      {
        name: 'Classic Navy Blue Belted Nida Abaya',
        slug: 'classic-navy-blue-belted-nida-abaya',
        description: 'Sophisticated navy blue closed abaya featuring a detachable waist tie belt for custom styling.',
        shortDescription: 'Navy blue closed abaya with detachable belt.',
        category: catMap['nida-abaya'],
        price: 4800,
        sku: 'HYT-NID-003',
        stock: 0,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Navy Blue'],
        fabric: 'Korean Soft Nida',
        careInstructions: 'Machine wash delicate cycle.',
        images: [
          { url: IMG.nidaCat, alt: 'Classic Navy Blue Belted Nida Abaya', order: 0 },
          { url: IMG.nida1, alt: 'Navy Blue Abaya Belt Detail', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['navy blue', 'belted', 'nida'],
        ratingAvg: 4.5,
        ratingCount: 12,
        soldCount: 30,
      },

      // 2. Dubai / Kaftan Style (3 items)
      {
        name: 'Royal Gold Trimmed Dubai Kaftan Abaya',
        slug: 'royal-gold-trimmed-dubai-kaftan-abaya',
        description: 'Majestic Dubai style kaftan highlighted by metallic gold thread borders and a flowing butterfly silhouette.',
        shortDescription: 'Royal gold trim kaftan abaya with flowing drape.',
        category: catMap['dubai-kaftan-style'],
        price: 8900,
        salePrice: 7999,
        sku: 'HYT-DUB-001',
        stock: 15,
        lowStockThreshold: 5,
        sizes: ['Free Size'],
        colors: ['Black', 'Gold'],
        fabric: 'Dubai Satin Silk & Nida',
        careInstructions: 'Dry clean only.',
        images: [
          { url: IMG.dubai1, alt: 'Royal Gold Trimmed Dubai Kaftan Abaya', order: 0 },
          { url: IMG.dubaiCat, alt: 'Dubai Kaftan Flow Detail', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['dubai', 'kaftan', 'gold trim', 'luxury'],
        ratingAvg: 5.0,
        ratingCount: 20,
        soldCount: 50,
      },
      {
        name: 'Butterfly Cut Oversized Maroon Kaftan',
        slug: 'butterfly-cut-oversized-maroon-kaftan',
        description: 'Deep maroon chiffon overlay kaftan with inner soft Nida lining and pleated cuffs.',
        shortDescription: 'Maroon butterfly cut kaftan with chiffon overlay.',
        category: catMap['dubai-kaftan-style'],
        price: 7500,
        salePrice: 6800,
        sku: 'HYT-DUB-002',
        stock: 12,
        lowStockThreshold: 5,
        sizes: ['Free Size'],
        colors: ['Maroon'],
        fabric: 'Chiffon & Nida Blend',
        careInstructions: 'Hand wash gently in cold water.',
        images: [
          { url: IMG.dubai2, alt: 'Butterfly Cut Maroon Kaftan Front View', order: 0 },
          { url: IMG.dubaiCat, alt: 'Butterfly Cut Kaftan Drape', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['maroon', 'butterfly kaftan', 'chiffon'],
        ratingAvg: 4.8,
        ratingCount: 6,
        soldCount: 14,
      },
      {
        name: 'Luxury Pleated Dubai Layered Kaftan',
        slug: 'luxury-pleated-dubai-layered-kaftan',
        description: 'Subtle dusty pink multi-layered pleated kaftan styled straight from Dubai fashion week.',
        shortDescription: 'Dusty pink multi-layered pleated kaftan.',
        category: catMap['dubai-kaftan-style'],
        price: 9500,
        salePrice: 8500,
        sku: 'HYT-DUB-003',
        stock: 4,
        lowStockThreshold: 5,
        sizes: ['Free Size'],
        colors: ['Dusty Pink'],
        fabric: 'Pure Dubai Crape',
        careInstructions: 'Dry clean recommended.',
        images: [
          { url: IMG.dubaiCat, alt: 'Luxury Pleated Dubai Layered Kaftan', order: 0 },
          { url: IMG.dubai1, alt: 'Dubai Kaftan Layer Detail', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['dusty pink', 'pleated', 'dubai fashion'],
        ratingAvg: 4.9,
        ratingCount: 11,
        soldCount: 22,
      },

      // 3. Embroidered Abaya (3 items)
      {
        name: 'Hand-Embroidered Floral Sleeve Abaya',
        slug: 'hand-embroidered-floral-sleeve-abaya',
        description: 'Exquisite silver wire hand-embroidered floral vines down the full length of sleeve cuffs.',
        shortDescription: 'Black abaya with intricate silver floral sleeve embroidery.',
        category: catMap['embroidered-abaya'],
        price: 8200,
        salePrice: 7499,
        sku: 'HYT-EMB-001',
        stock: 18,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Silver'],
        fabric: 'Nida Linen Blend',
        careInstructions: 'Hand wash inside out in cold water.',
        images: [
          { url: IMG.embCat, alt: 'Hand-Embroidered Floral Sleeve Abaya', order: 0 },
          { url: IMG.nidaCat, alt: 'Floral Embroidery Sleeve Close-up', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['hand embroidered', 'silver work', 'floral'],
        ratingAvg: 4.9,
        ratingCount: 18,
        soldCount: 35,
      },
      {
        name: 'Moroccan Resham Work Flare Abaya',
        slug: 'moroccan-resham-work-flare-abaya',
        description: 'Plum colored umbrella flare abaya decorated with rich gold Moroccan resham thread embroidery on bodice.',
        shortDescription: 'Plum flare abaya with gold Moroccan resham embroidery.',
        category: catMap['embroidered-abaya'],
        price: 9800,
        salePrice: 8900,
        sku: 'HYT-EMB-002',
        stock: 10,
        lowStockThreshold: 5,
        sizes: ['M', 'L', 'XL', 'XXL'],
        colors: ['Plum', 'Gold'],
        fabric: 'Korean Nida',
        careInstructions: 'Dry clean only.',
        images: [
          { url: IMG.embCat, alt: 'Moroccan Resham Work Flare Abaya', order: 0 },
          { url: IMG.dubai1, alt: 'Moroccan Resham Embroidery Detail', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['moroccan', 'resham embroidery', 'flare'],
        ratingAvg: 4.6,
        ratingCount: 7,
        soldCount: 11,
      },
      {
        name: 'Pearl & Thread Embroidered Festive Abaya',
        slug: 'pearl-thread-embroidered-festive-abaya',
        description: 'Champagne tone organza jacket over nida abaya studded with hand-stitched pearls and tonal embroidery.',
        shortDescription: 'Champagne festive jacket abaya with pearl work.',
        category: catMap['embroidered-abaya'],
        price: 10500,
        salePrice: 9499,
        sku: 'HYT-EMB-003',
        stock: 25,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Champagne'],
        fabric: 'Organza & Nida',
        careInstructions: 'Dry clean only.',
        images: [
          { url: IMG.embCat, alt: 'Pearl & Thread Embroidered Festive Abaya', order: 0 },
          { url: IMG.partyCat, alt: 'Pearl Detailing View', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['pearl work', 'champagne', 'festive'],
        ratingAvg: 5.0,
        ratingCount: 14,
        soldCount: 28,
      },

      // 4. Casual / Daily Wear (3 items)
      {
        name: 'Minimalist Everyday Button-Down Abaya',
        slug: 'minimalist-everyday-button-down-abaya',
        description: 'Lightweight, wrinkle-resistant zoom fabric abaya with functional front buttons and deep side pockets.',
        shortDescription: 'Button-down Zoom fabric daily wear abaya with pockets.',
        category: catMap['casual-daily-wear'],
        price: 3800,
        salePrice: 3299,
        sku: 'HYT-CAS-001',
        stock: 30,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Beige', 'Black'],
        fabric: 'Breathable Zoom Fabric',
        careInstructions: 'Machine wash cool, tumble dry low.',
        images: [
          { url: IMG.casualCat, alt: 'Minimalist Everyday Button-Down Abaya', order: 0 },
          { url: IMG.nida1, alt: 'Button Detail Close-up', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['casual', 'pockets', 'button down', 'everyday'],
        ratingAvg: 4.8,
        ratingCount: 24,
        soldCount: 65,
      },
      {
        name: 'Soft Linen Pocket Casual Abaya',
        slug: 'soft-linen-pocket-casual-abaya',
        description: 'Olive green pure cotton linen abaya featuring relaxed raglan sleeves and utilitarian front flap pockets.',
        shortDescription: 'Olive green cotton linen abaya with flap pockets.',
        category: catMap['casual-daily-wear'],
        price: 4200,
        salePrice: 3699,
        sku: 'HYT-CAS-002',
        stock: 22,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Olive Green'],
        fabric: 'Cotton Linen',
        careInstructions: 'Machine wash cool with like colors.',
        images: [
          { url: IMG.casualCat, alt: 'Soft Linen Pocket Casual Abaya', order: 0 },
          { url: IMG.nida2, alt: 'Pocket and Texture View', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['linen', 'olive green', 'casual'],
        ratingAvg: 4.7,
        ratingCount: 9,
        soldCount: 21,
      },
      {
        name: 'Lightweight Zip-Up Sports Abaya',
        slug: 'lightweight-zip-up-sports-abaya',
        description: 'Charcoal grey stretch Lycra blend active abaya designed with full front zip and fitted elastic cuffs.',
        shortDescription: 'Charcoal zip-up active sports abaya with elastic cuffs.',
        category: catMap['casual-daily-wear'],
        price: 3500,
        sku: 'HYT-CAS-003',
        stock: 0,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Charcoal Grey'],
        fabric: 'Jersey Lycra Blend',
        careInstructions: 'Machine wash cold.',
        images: [
          { url: IMG.casualCat, alt: 'Lightweight Zip-Up Sports Abaya', order: 0 },
          { url: IMG.nida2, alt: 'Front Zipper View', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['sports', 'zip up', 'charcoal', 'casual'],
        ratingAvg: 4.4,
        ratingCount: 15,
        soldCount: 40,
      },

      // 5. Party Wear Abaya (3 items)
      {
        name: 'Crystal Studded Velvet Trimmed Party Abaya',
        slug: 'crystal-studded-velvet-trimmed-party-abaya',
        description: 'High-lux deep black abaya featuring rich velvet lapels embellished with Swarovski-style micro crystals.',
        shortDescription: 'Black abaya with crystal studded velvet lapels.',
        category: catMap['party-wear-abaya'],
        price: 11500,
        salePrice: 9999,
        sku: 'HYT-PRT-001',
        stock: 14,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Deep Black'],
        fabric: 'Velvet & Korean Silk Nida',
        careInstructions: 'Dry clean only.',
        images: [
          { url: IMG.partyCat, alt: 'Crystal Studded Velvet Trimmed Party Abaya', order: 0 },
          { url: IMG.embCat, alt: 'Crystal Velvet Trim Close-up', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['party wear', 'velvet', 'crystal work', 'luxury'],
        ratingAvg: 5.0,
        ratingCount: 31,
        soldCount: 58,
      },
      {
        name: 'Shimmering Sequin Flare Luxury Abaya',
        slug: 'shimmering-sequin-flare-luxury-abaya',
        description: 'Midnight blue floor length gown abaya with cascading sequin motifs catching the light from every angle.',
        shortDescription: 'Midnight blue flared abaya with sparkling sequin details.',
        category: catMap['party-wear-abaya'],
        price: 12000,
        salePrice: 10800,
        sku: 'HYT-PRT-002',
        stock: 8,
        lowStockThreshold: 5,
        sizes: ['M', 'L', 'XL'],
        colors: ['Midnight Blue'],
        fabric: 'Sequin Organza',
        careInstructions: 'Dry clean only.',
        images: [
          { url: IMG.partyCat, alt: 'Shimmering Sequin Flare Luxury Abaya', order: 0 },
          { url: IMG.dubai1, alt: 'Sequin Reflection Close-up', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['midnight blue', 'sequin', 'occasion wear'],
        ratingAvg: 4.9,
        ratingCount: 16,
        soldCount: 29,
      },
      {
        name: 'Bridal Elegance Metallic Thread Abaya',
        slug: 'bridal-elegance-metallic-thread-abaya',
        description: 'Rose gold woven metallic thread jacquard coat abaya designed for weddings and bridal trousseaus.',
        shortDescription: 'Rose gold jacquard metallic thread coat abaya.',
        category: catMap['party-wear-abaya'],
        price: 12500,
        salePrice: 11200,
        sku: 'HYT-PRT-003',
        stock: 16,
        lowStockThreshold: 5,
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Rose Gold'],
        fabric: 'Jacquard & Nida',
        careInstructions: 'Dry clean only.',
        images: [
          { url: IMG.partyCat, alt: 'Bridal Elegance Metallic Thread Abaya', order: 0 },
          { url: IMG.dubai1, alt: 'Jacquard Fabric Detail', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['rose gold', 'bridal', 'jacquard', 'party wear'],
        ratingAvg: 4.8,
        ratingCount: 10,
        soldCount: 22,
      },

      // 6. Kids Abaya (3 items)
      {
        name: 'Little Princess Lace Trimmed Kids Abaya',
        slug: 'little-princess-lace-trimmed-kids-abaya',
        description: 'Adorable soft pink and black lightweight abaya for young girls with delicate scalloped lace borders.',
        shortDescription: 'Pink and black kids abaya with scalloped lace border.',
        category: catMap['kids-abaya'],
        price: 3200,
        salePrice: 2799,
        sku: 'HYT-KID-001',
        stock: 25,
        lowStockThreshold: 5,
        sizes: ['24', '28', '32', '36', '40'],
        colors: ['Pink', 'Black'],
        fabric: 'Soft Korean Nida',
        careInstructions: 'Gentle hand wash.',
        images: [
          { url: IMG.kidsCat, alt: 'Little Princess Lace Trimmed Kids Abaya', order: 0 },
          { url: IMG.nidaCat, alt: 'Lace Hem Close-up', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['kids', 'pink', 'lace', 'girls abaya'],
        ratingAvg: 4.9,
        ratingCount: 17,
        soldCount: 38,
      },
      {
        name: 'School & Madrassa Simple Kids Abaya',
        slug: 'school-madrassa-simple-kids-abaya',
        description: 'Durable jet black micro Nida abaya ideal for daily school, quran class, and routine wear.',
        shortDescription: 'Plain black durable kids abaya for daily madrassa wear.',
        category: catMap['kids-abaya'],
        price: 2900,
        salePrice: 2499,
        sku: 'HYT-KID-002',
        stock: 20,
        lowStockThreshold: 5,
        sizes: ['24', '28', '32', '36', '40'],
        colors: ['Black'],
        fabric: 'Micro Nida',
        careInstructions: 'Machine wash cool.',
        images: [
          { url: IMG.kidsCat, alt: 'School & Madrassa Simple Kids Abaya', order: 0 },
          { url: IMG.nida1, alt: 'Madrassa Abaya Detail', order: 1 },
        ],
        isFeatured: false,
        isActive: true,
        isDeleted: false,
        tags: ['kids', 'madrassa', 'black abaya', 'school'],
        ratingAvg: 4.7,
        ratingCount: 13,
        soldCount: 45,
      },
      {
        name: 'Festive Embroidered Mini Abaya Set',
        slug: 'festive-embroidered-mini-abaya-set',
        description: 'Charming lilac tone kids abaya with matching embroidered Sheila scarf for eid and family gatherings.',
        shortDescription: 'Lilac kids abaya with mini embroidered matching Sheila.',
        category: catMap['kids-abaya'],
        price: 3900,
        salePrice: 3450,
        sku: 'HYT-KID-003',
        stock: 15,
        lowStockThreshold: 5,
        sizes: ['28', '32', '36', '40'],
        colors: ['Lilac'],
        fabric: 'Nida & Lace',
        careInstructions: 'Hand wash cold.',
        images: [
          { url: IMG.kidsCat, alt: 'Festive Embroidered Mini Abaya Set', order: 0 },
          { url: IMG.embCat, alt: 'Embroidered Scarf Detail', order: 1 },
        ],
        isFeatured: true,
        isActive: true,
        isDeleted: false,
        tags: ['kids', 'festive', 'lilac', 'eid collection'],
        ratingAvg: 5.0,
        ratingCount: 8,
        soldCount: 16,
      },
    ];

    console.log('Inserting products...');
    const createdProducts = await Product.insertMany(productsData);
    console.log(`${createdProducts.length} products inserted successfully.`);

    console.log('\n================ SEED SUMMARY ================');
    console.log(`Categories inserted: ${createdCategories.length}`);
    console.log(`Products inserted:   ${createdProducts.length}`);
    console.log('==============================================\n');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
